name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --production

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
          NODE_ENV: production
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NODE_ENV
          script: |
            echo "Starting deployment"
            echo "Pulling latest code from repository"
              cd /var/www/wisdom.short.cool
              git pull origin main
              npm install --production
              pm2 restart wisdom || pm2 start npm --name wisdom -- start
              pm2 save
              echo "Deployment complete"
