name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
          NODE_ENV: production
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NODE_ENV
          script: |
           echo "Starting deployment"
            if [ -d "/var/www/wisdom.short.cool" ]; then
              echo "Directory exists, removing it"
              sudo rm -rf /var/www/wisdom.short.cool
            fi
            echo "Creating and cloning repository"
            sudo mkdir -p /var/www/wisdom.short.cool
            sudo git clone https://github.com/armandolio/the-mind-hacks /var/www/wisdom.short.cool --depth 1
            cd /var/www/wisdom.short.cool
            sudo yarn install --production
            sudo pm2 restart wisdom || sudo pm2 start yarn --name "wisdom" -- start
