name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
          NODE_ENV: production
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NODE_ENV
          script: |
            echo "Starting deployment"
            if [ ! -d " /var/www/wisdom.short.cool" ]; then
              echo "Directory does not exist, creating and cloning repository"
              sudo mkdir -p  /var/www/wisdom.short.cool
              git clone https://github.com/armandolio/the-mind-hacks /var/www/wisdom.short.cool --depth 1
            fi
            cd /var/www/wisdom.short.cool
            if [ ! -d ".git" ]; then
              echo "Not a git repository, initializing"
              git init
              git remote add origin https://github.com/armandolio/the-mind-hacks
            fi
            git fetch --all
            git reset --hard origin/main
            yarn install --production
            pm2 restart wisdom || pm2 start yarn --name "wisdom" -- start
